export const CHECKINS_HAS_ERRORED = 'CHECKINS_HAS_ERRORED';
export const CHECKINS_IS_LOADING = 'CHECKINS_IS_LOADING';
export const CHECKINS_FETCH_DATA_SUCCESS = 'CHECKINS_FETCH_DATA_SUCCESS';
export const CHECKINS_DELETE_SUCCESS = 'CHECKINS_DELETE_SUCCESS';
export const CHECKINS_ADD_SUCCESS = 'CHECKINS_ADD_SUCCESS';
